version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=${NODE_ENV}
      - VITE_APP_BASE_API_PRODUCTION=${VITE_APP_BASE_API_PRODUCTION}
      - VITE_APP_BASE_API_STAGING=${VITE_APP_BASE_API_STAGING}
