# .github/workflows/code-quality-ci.yml
name: Code Quality CI

# 触发工作流的事件
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality-check:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm@9.15.4

      # 4. 安装项目依赖
      - name: Install dependencies
        run: pnpm install

      # 5. ESLint 代码质量检查
      - name: Run ESLint
        run: pnpm run lint
        continue-on-error: false

      # 6. Prettier 代码格式化检查
      - name: Run Prettier check
        run: pnpm run prettier:check
        continue-on-error: false
